export type AgentId =
  | 'gerente'
  | 'secretaria'
  | 'colegio-lucia'
  | 'salud-familiar'
  | 'finanzas-familiares'
  | 'educacion-aprendizaje'
  | 'conocimiento-obsidian'
  | 'pmo'
  | 'tecnico'
  | 'ventas'
  | 'marketing'
  | 'legal'
  | 'finanzas-dmente'
  | 'producto-vertice'
  | 'producto-synapse'
  | 'whatsapp-conversaciones'
export type Section = 'office' | 'agents' | 'requests' | 'settings'
export type Message = { from: 'agent' | 'user'; text: string; time: string }
export type AgentView = { name: string; role: string; normal: string; attention: string; status: string; color: string; visibleInOffice?: boolean }
